// Generated by unRap v1.06 by Kegetys

class CfgWeapons
{
	class CannonCore;// External class reference
	class MGun;
	class autocannon_Base_F;
	class RocketPods;
	class RifleCore;

	class Rifle: RifleCore
	{
		class WeaponSlotsInfo;
	};

	//// ПИОНЕР
	class sc9_IFC_nw42: RocketPods
	{
		reloadTime = 20;
		magazineReloadTime = 20;
		magazines[] = { "sc9_5Rnd_NW42_HE"};
	};
	class ifr_lg40: CannonCore
	{
		reloadTime = 6;
		magazineReloadTime = 6;
		magazines[] = {"ifr_lg40_HE","ifr_lg40_AP"};
	};
	//// ПИОНЕР

	class Rifle_Base_F;
	class Rifle_Long_Base_F: Rifle_Base_F
	{
		class WeaponSlotsInfo;
	};
	class LIB_LMG: Rifle_Long_Base_F
	{
		class WeaponSlotsInfo: WeaponSlotsInfo {};
	};

	class LIB_MG42: LIB_LMG
	{
		class WeaponSlotsInfo: WeaponSlotsInfo {};
	};

	class LIB_MG342: LIB_MG42
	{
		class WeaponSlotsInfo: WeaponSlotsInfo {};
	};

	class ifa3_mg34_tromm: LIB_MG342
	{
		magazines[] = {"lib_75Rnd_792x57","lib_75Rnd_792x57_ss","lib_75Rnd_792x57_SMK"};
		autoReload = true;

	};
	class LIB_AntiAirCannon_base: CannonCore
	{
		class manual;
	};
	class LIB_61k: LIB_AntiAirCannon_base
	{
		magazineReloadTime = 0.5;
		autoReload = true;
		magazines[] = {"LIB_5x_61k","LIB_5x_61kAP"};
	};

	class LIB_TankMGun_base: Mgun
	{
		class manual;
	};
	class Lib_dt29: Lib_tankmgun_base
{
		magazines[] = {"lib_63Rnd_762x54"};
		autoReload = true;
	};
	class ifa3_DT29: LIB_DT29
{
		magazines[] = {"lib_63Rnd_762x54"};
	};
	class LIB_StaticGunCannon_base;
	class LIB_ZIS3_base: LIB_StaticGunCannon_base
	{
		reloadTime = 2;
		magazineReloadTime = 2;
		autoReload = true;
		magazines[] = {"LIB_OF350_HE","LIB_BR350B_AP","LIB_BR350P_APCR"};
	};
	class ifa3_ZIS5: LIB_ZIS3_base
	{
		reloadTime = 6;
		magazineReloadTime = 6;
	};

	class LIB_Pak40_base: LIB_StaticGunCannon_base
	{
		reloadTime = 2;
		magazineReloadTime = 2;
		autoReload = true;
		magazines[] = { "LIB_SprGr34_KWK40_HE","LIB_PzGr39_KWK40_AP","LIB_PzGr40_KWK40_APCR"};
	};
	class LIB_TankCannon_base;
	class LIB_F34_base: LIB_TankCannon_base
	{
		reloadTime = 6;
		magazineReloadTime = 6;
		autoReload = true;
		magazines[] = {"LIB_OF350_HE","LIB_BR350B_AP","LIB_BR350P_APCR"};
	};

	class LIB_P27: CannonCore
	{
		magazineReloadTime = 2;
		magazines[] = {"ifa3_UBR353","ifa3_UOF353","ifa3_USHC353"};
		class manual: CannonCore
		{
			reloadTime = 2;
			autoReload = true;
		};
	};

	class IFA3_KWK_39: autocannon_Base_F
{
		reloadTime = 4;
		magazineReloadTime = 4;
		autoReload = true;
		magazines[] = {"IFa3_1x_SprGr38_KWK_39","IFa3_1x_Pzgr39_KWK_39","IFa3_1x_Pzgr40_KWK_39"};
		class manual: CannonCore
		{
			reloadTime = 4;
			autoReload = true;
		};
	};
	class IFA3_KWK_37: autocannon_Base_F
	{
		magazines[] = {"IFa3_1x_SprGr34_KWK_37","IFa3_1x_K_Gr_rotPz_KWK_37","IFa3_1x_HI_Gr38C_KWK_37"};
		reloadTime = 5;
		magazineReloadTime = 5;
		autoReload = true;
		class manual: CannonCore
		{
			reloadTime = 5;
			autoReload = true;
		};
	};

	class LIB_KWK_38: autocannon_Base_F
	{
		reloadTime = 0.134;
		magazineReloadTime = 4;
		autoReload = true;
		magazines[] = {"LIB_10x_SprGr_KWK_38","LIB_10x_Pzgr_KWK_38","LIB_10x_Pzgr40_KWK_38"};

		class manual: CannonCore
		{
			autoFire = true;
			autoReload = true;
			reloadTime = 0.134;
			magazineReloadTime = 4;
		};
	};
	class IFA3_K_20: autocannon_Base_F
	{
		magazines[] = {"IFa3_1x_0240_k_20","IFa3_1x_BR240_k_20","IFa3_1x_BR240P_k_20"};
		reloadTime = 3.5;
		magazineReloadTime = 3.5;
		autoReload = true;

		class manual: CannonCore
		{
			reloadTime = 3.5;
			autoReload = true;
		};
	};

	class ifa3_TNSH20: autocannon_Base_F {

		magazineReloadTime = 12;
		autoReload = true;
		class manual: CannonCore
		{
			autoFire = true;
			autoReload = true;
			reloadTime = 0.08;
		};
	};

	class IFA3_PaK_38: CannonCore
	{
		reloadTime = 2;
		magazineReloadTime = 2;
		autoReload = true;
		magazines[] = {"IFa3_1x_Pzgr40_KWK_39","IFa3_1x_Pzgr39_KWK_39","IFa3_1x_SprGr38_KWK_39"};
		class manual: CannonCore
		{
			reloadTime = 2;
			autoReload = true;
		};
	};
	class LIB_M3_L40_base: LIB_TankCannon_base
	{
		reloadTime = 6;
		magazineReloadTime = 6;
		autoReload = true;
		magazines[] = {"LIB_M42A1_M1_HE","LIB_M61_M1_AP","LIB_T45_M1_APCR"};
	};
	class LIB_KwK40_L48_base: LIB_TankCannon_base
	{
		reloadTime = 7;
		magazineReloadTime = 7;
		autoReload = true;
		magazines[] = { "LIB_SprGr34_KWK40_HE","LIB_PzGr39_KWK40_AP","LIB_PzGr40_KWK40_APCR"};
	};
	class LIB_StuK40_L48_base: LIB_TankCannon_base
	{
		reloadTime = 6;
		magazineReloadTime = 6;
	};
	class LIB_LeFH18_base_L28: LIB_StuK40_L48_base
	{
		reloadTime = 6;
		magazineReloadTime = 6;
		magazines[] = { "LIB_FHGr_leFH18_HE","LIB_PzGr_leFH18_AP","LIB_GR39rot_leFH18_HI"};
	};
	class IFA3_M10T: LIB_StuK40_L48_base
	{
	reloadTime = 19;
	magazineReloadTime = 19;
	magazines[] = {"IFA3_OF530_HE","IFA3_G530_AP"};
	};

	class LIB_FlaK_38_X4: LIB_AntiAirCannon_base
	{
		autoReload = true;
		magazineReloadTime = 6;
		magazines[] = { "LIB_80x_SprGr_FlaK_38"};
		class manual: manual
		{
			autoFire = true;
			autoReload = true;
			reloadTime = 0.04;
		};
	};
};
