// Generated by unRap v1.06 by Kegetys

class Extended_PreStart_EventHandlers
{
	class ace_ifa3reload
	{
		init = "call compile preProcessFileLineNumbers '\z\ifa3_comp_ace\addons\reload\XEH_preStart.sqf'";
	};
};
