// Generated by unRap v1.06 by Kegetys

class Extended_FiredBIS_EventHandlers
{
	class Tank_F
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class LIB_StaticCannon_base
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class LIB_StaticCanon_base
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class Car
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class StaticMGWeapon
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class StaticMortar
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class sc9_IFC_Nebelw42
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
	class ifr_lg40_base
	{
		class ace_ifa3reload
		{
			firedBIS = "_this call ace_ifa3reload_fnc_handleFired";
		};
	};
};
