// Generated by unRap v1.06 by Kegetys

class ACE_Settings
{
	class ace_mk6mortar_airResistanceEnabled
	{
		value = 0;
		typeName = BOOL;
		isClientSetable = 0;
	};

	class ace_mk6mortar_allowComputerRangefinder
	{
		value = 0;
		typeName = BOOL;
		isClientSetable = 0;
	};

	class ace_mk6mortar_allowCompass
	{
		value = 1;
		typeName = BOOL;
		isClientSetable = 0;
	};

	class ace_mk6mortar_useAmmoHandling
	{
		value = 1;
		typeName = BOOL;
		isClientSetable = 0;
	};
};
