// Generated by unRap v1.06 by Kegetys

class Extended_FiredBIS_EventHandlers
{
	class rhs_2b14_82mm_Base
	{
		class ace_ifa3mortar
		{
			firedBIS = "_this call ace_ifa3mortar_fnc_handleFired";
		};
	};

	class RHS_M252_Base
	{
		class ace_ifa3mortar
		{
			firedBIS = "_this call ace_ifa3mortar_fnc_handleFired";
		};
	};

	class rhs_D30_base
	{
		class ace_ifa3mortar
		{
			firedBIS = "_this call ace_ifa3mortar_fnc_handleFired";
		};
	};

	class RHS_M119_base
	{
		class ace_ifa3mortar
		{
			firedBIS = "_this call ace_ifa3mortar_fnc_handleFired";
		};
	};
};
