// Generated by unRap v1.06 by Kegetys

class Extended_PreStart_EventHandlers
{
	class ace_mk6mortar
	{
		init = "call compile preProcessFileLineNumbers '\z\ace\addons\mk6mortar\XEH_preStart.sqf'";
	};
};
