// Generated by unRap v1.06 by Kegetys

class Extended_PostInit_EventHandlers
{
	class ace_ifa3mortar
	{
		clientInit = "call compile preProcessFileLineNumbers '\z\ifa3_comp_ace\addons\mortar\XEH_clientInit.sqf'";
	};
};
