// Generated by unRap v1.06 by Kegetys

class Extended_PreInit_EventHandlers
{
	class ace_ifa3mortar
	{
		init = "call compile preProcessFileLineNumbers '\z\ifa3_comp_ace\addons\mortar\XEH_preInit.sqf'";
	};
};
